### ISSUE TITLE
Come up with hypotheses to test with the model based on culling, for example

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/raccoon_simulation#11]
@zanyzooks

**Comment by SBWeinstein** [comment]
1.  Raccoon population targeted strategies: (simulation runs)
   a.  Culling: add an extra source of raccoon mortality
   i.  All age classes equally (eg, through distribution of poison bait)
   ii. Age specific (eg. Active trapping to remove most heavily infected juveniles. 
2.  Cull animals under a year (juveniles).  
   iii.    Cull raccoons with high human overlap 
   a.  Remove racs with overlap .9-1 (but there is nothing to stop the next generation of raccoons from reestablishing in that habitat)
   i.  Realistically, this is what is happening in most urban nuisance animal removal programs.
   b.  Birth control for raccoons: reduce number of raccoons that reproduce
   i.  All though this doesn’t appear to have ever been implemented in raccoon populations, a product does exist, and there are successful (?) examples of its use in other wildlife populations
   ii. Reduce reproduction (a greater fraction of the population does not have a litter)
   c.  Block raccoon access to human areas
   i.  Raccoons cannot be in  1 habitats
3.  Also consider reducing carrying capacity, or something, because we have now removed 10% (or whatever coincides with amount of habitat blocked) of the suitable habitat for the population
4.  When assigning overlap vector, include only 0-0.9, and set the 1 level to 0 risk with calculating total human risk.
5.  Parasite targeted strategies
   a.  Antihelminthic baiting
   i.  Distribute bait containing deworming medication throughout landscape (eg dropping is from airplanes like the do with rabies vaccines).  This has been tested at a small scale and, at least locally, appears to lead to a 30% reduction in prevalence ().
   ii. Model as resetting worm pop to zero for some set of raccoons alive.  Assume if get bait, removes all worms, so effectiveness of baiting be set as what fraction of pop gets dewormed (ate bait). 
   iii.    baiting only in human overlap zone (more like hand distribution).
   b.  Remove latrines deposited in high human areas
   i.  Not explicitly modelling eggs, but latrines are the cumulative egg production from the worms in the raccoons in that area.  
   ii. Actively removing latrines in 0.9-1 habitats would be the same as replacing worm counts in those raccoon with zero\* for calculating human risk.  But, for population matrices, raccoons maintain their worms.
6.  *zero assumes 100% success at finding and removing latrines, could be scaled with some sort of latrine removal efficiency
