### ISSUE TITLE
Find a estimate for the bait loss parameter

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/raccoon_simulation#36]

**Comment by SBWeinstein** [comment]
Smyser et al 2013- baiting trials with cameras- raccoons removed 44% of bait.

for simplicity I like that we assume that baits work 100%, although field trials to date show that they don't yet for this parasite (due to both raccoons not always eating the full bait and potential degradation of drug in bait)  But, this is probability a bait optimization problem, and if they increased the dose they would be more effective.   

In experimental bait trials from Smyser et al 2015 they gave 16 infected racs the bait.  11/16 were completely dewormed and  3/16 were partially dewormed. 

we could add heterogeneity in bait effectiveness by modifying our got_bait/kill worms.  
currently we set all new_cohorts to zero if got_bait.  

instead of setting all cohorts to zero we could multiply all cohorts by a value pulled from a distribution (0,1) with mostly zeros (kill all), but some chance of >0 to 1 values.

This makes baiting less effective overall, and adds more heterogeneity in response.  But would probably be easily swamped out in the model by increasing the bait density, and (in real life) by increasing drug concentration per bait. Worth adding complexity?

Also, note that we need to cap max bait application because it can be toxic above about 7x the recommended dose

**Comment by mqwilber** [comment]
Decided to treat bait as 100% effective, because we are assuming that someone would actually run trials to make sure drug is effective.
