### ISSUE TITLE
Encounter probability should be proportional to to raccoon prevalence

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/raccoon_simulation#5]
Something like

``` r
encounter_prob = num_racs_w_worms / tot_racs_alive
```

This will allow the encounter prob to more realistically vary with prevalence

**Comment by mqwilber** [comment]
We've done it and broken it!

When there are no `prev = 0` no raccoons can be infected.  We need to and in some past history of prevalence such that even if all raccoons are uninfected there is still some probability of infection.

@zanyzooks is thinking about it.

**Comment by SBWeinstein** [comment]
we now keep track of the prevalence at each time point.  if we assume that eggs decay in the environment as an exponential function we can then have encounter_prob = Sum of the prevalence*decay for each time point.  If these sum to greater than one the environment is "saturated" with eggs and encounter prob is set to one.  This doesn't fix the problem when we start with a population at all zeros, but maybe instead we just start of with a partially infected raccoon population?
We might also want to keep track of this egg decay when we think about human risk.  Because risk isn't just from the eggs produced right now, any that remain in the environment are also a risk

**Comment by mqwilber** [comment]
Done
